name: neu
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _tflow_select=2.1.0=gpu
  - alabaster=0.7.12=py37_0
  - asn1crypto=0.24.0=py37_0
  - astroid=2.2.5=py37_0
  - attrs=19.1.0=py37_1
  - babel=2.6.0=py37_0
  - backcall=0.1.0=py37_0
  - blas=1.0=mkl
  - bleach=3.1.0=py37_0
  - ca-certificates=2019.11.27=0
  - certifi=2019.11.28=py37_0
  - cffi=1.12.3=py37h7a1dbc1_0
  - chardet=3.0.4=py37_1
  - cloudpickle=1.0.0=py_0
  - colorama=0.4.1=py37_0
  - cryptography=2.6.1=py37h7a1dbc1_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.0=cuda10.0_0
  - cycler=0.10.0=py37_0
  - cytoolz=0.9.0.1=py37hfa6e2cd_1001
  - dask-core=2.0.0=py_0
  - decorator=4.4.0=py37_1
  - defusedxml=0.6.0=py_0
  - docutils=0.14=py37_0
  - entrypoints=0.3=py37_0
  - fastcache=1.1.0=py37he774522_0
  - freetype=2.9.1=ha9979f8_1
  - h5py=2.9.0=py37h5e291fa_0
  - hdf5=1.10.4=h7ebc959_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha66f8fd_1
  - idna=2.8=py37_0
  - imageio=2.5.0=py37_0
  - imagesize=1.1.0=py37_0
  - intel-openmp=2019.3=203
  - ipykernel=5.1.0=py37h39e3cac_0
  - ipython=7.5.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.5.1=py_0
  - isort=4.3.19=py37_0
  - jedi=0.13.3=py37_0
  - jinja2=2.10.1=py37_0
  - jpeg=9b=hb83a4c4_2
  - jsonschema=3.0.1=py37_0
  - jupyter=1.0.0=py37_7
  - jupyter_client=5.2.4=py37_0
  - jupyter_console=6.0.0=py37_0
  - jupyter_core=4.4.0=py37_0
  - keras-base=2.2.4=py37_0
  - keras-gpu=2.2.4=0
  - keyring=18.0.0=py37_0
  - kiwisolver=1.1.0=py37ha925a31_0
  - lazy-object-proxy=1.4.1=py37he774522_0
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.8.0=h7bd577a_0
  - libsodium=1.0.16=h9d3ae62_0
  - libtiff=4.0.9=hf1753bf_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.1.1=py37he774522_0
  - matplotlib=3.0.3=py37hc8f65d3_0
  - matplotlib-base=3.1.1=py37h2852a4a_0
  - mccabe=0.6.1=py37_1
  - mistune=0.8.4=py37he774522_0
  - mkl=2019.3=203
  - mkl_fft=1.0.12=py37h14836fe_0
  - mkl_random=1.0.2=py37h343c172_0
  - mock=3.0.5=py37_0
  - mpmath=1.1.0=py37_0
  - msys2-conda-epoch=20160418=1
  - nbconvert=5.5.0=py_0
  - nbformat=4.4.0=py37_0
  - networkx=2.3=py_0
  - notebook=5.7.8=py37_0
  - numpy-base=1.16.3=py37hc3f5095_0
  - numpydoc=0.9.1=py_0
  - olefile=0.46=py_0
  - openssl=1.1.1d=he774522_3
  - packaging=19.0=py37_0
  - pandas=0.24.2=py37ha925a31_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.4.0=py_0
  - patsy=0.5.1=py37_0
  - pickleshare=0.7.5=py37_0
  - pip=19.1.1=py37_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.9=py37_0
  - psutil=5.6.2=py37he774522_0
  - pycodestyle=2.5.0=py37_0
  - pycparser=2.19=py37_0
  - pyflakes=2.1.1=py37_0
  - pygments=2.4.0=py_0
  - pylint=2.3.1=py37_0
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.0=py_0
  - pyqt=5.9.2=py37h6538335_2
  - pyreadline=2.1=py37_1
  - pyrsistent=0.14.11=py37he774522_0
  - pysocks=1.7.0=py37_0
  - python=3.7.3=h8c8aaf0_1
  - python-dateutil=2.8.0=py37_0
  - pytz=2019.1=py_0
  - pywavelets=1.0.3=py37h452e1ab_1
  - pywin32=223=py37hfa6e2cd_1
  - pywinpty=0.5.5=py37_1000
  - pyyaml=5.1=py37he774522_0
  - pyzmq=18.0.0=py37ha925a31_0
  - qt=5.9.7=vc14h73c81de_0
  - qtawesome=0.5.7=py37_1
  - qtconsole=4.4.4=py_0
  - qtpy=1.7.1=py_0
  - requests=2.21.0=py37_0
  - rope=0.14.0=py_0
  - scikit-learn=0.20.3=py37h343c172_0
  - scipy=1.2.1=py37h29ff71c_0
  - send2trash=1.5.0=py37_0
  - shap=0.29.3=py37he350917_0
  - sip=4.19.8=py37h6538335_0
  - snowballstemmer=1.2.1=py37_0
  - sphinx=2.0.1=py_0
  - sphinxcontrib-applehelp=1.0.1=py_0
  - sphinxcontrib-devhelp=1.0.1=py_0
  - sphinxcontrib-htmlhelp=1.0.2=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.2=py_0
  - sphinxcontrib-serializinghtml=1.1.3=py_0
  - spyder=3.3.4=py37_0
  - spyder-kernels=0.4.4=py37_0
  - sqlite=3.28.0=he774522_0
  - statsmodels=0.10.1=py37h8c2d366_0
  - sympy=1.4=py37_0
  - tensorboard=1.13.1=py37h33f27b4_0
  - tensorflow=1.13.1=gpu_py37h83e5d6a_0
  - tensorflow-base=1.13.1=gpu_py37h871c8ca_0
  - tensorflow-estimator=1.13.0=py_0
  - terminado=0.8.2=py37_0
  - testpath=0.4.2=py37_0
  - tk=8.6.9=hfa6e2cd_1002
  - toolz=0.9.0=py_1
  - tornado=6.0.2=py37he774522_0
  - tqdm=4.32.2=py_0
  - traitlets=4.3.2=py37_0
  - urllib3=1.24.2=py37_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_1
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - werkzeug=0.15.4=py_0
  - widgetsnbextension=3.5.1=py37_0
  - win_inet_pton=1.1.0=py37_0
  - wincertstore=0.2=py37_0
  - winpty=0.4.3=4
  - wrapt=1.11.1=py37he774522_0
  - yaml=0.1.7=hc54c509_2
  - zeromq=4.3.1=h33f27b4_3
  - zlib=1.2.11=h62dcd97_3
  - pip:
    - absl-py==0.7.1
    - alibi==0.2.0
    - anchor-exp==0.0.0.6
    - astor==0.8.0
    - beautifulsoup4==4.7.1
    - blis==0.2.4
    - cymem==2.0.2
    - gast==0.2.2
    - grpcio==1.20.1
    - keras-applications==1.0.7
    - keras-preprocessing==1.0.9
    - lime==0.1.1.36
    - markdown==3.1
    - murmurhash==1.0.2
    - numpy==1.16.3
    - opencv-python==4.1.0.25
    - pillow==6.0.0
    - plac==0.9.6
    - preshed==2.0.1
    - protobuf==3.7.1
    - scikit-image==0.15.0
    - seaborn==0.9.0
    - setuptools==41.0.1
    - six==1.12.0
    - soupsieve==1.9.1
    - spacy==2.1.4
    - srsly==0.0.7
    - tensorflow-gpu==1.13.1
    - termcolor==1.1.0
    - thinc==7.0.4
    - wasabi==0.2.2
    - wheel==0.33.4


